version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    ports:
      - 8080:8080

    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

